/** 商品库卡片布局常量，商品卡片与虚拟网格必须共用同一高度。 */
export const PRODUCT_LIBRARY_CARD_HEIGHT = 432
export const PRODUCT_LIBRARY_GRID_GAP = 16
export const PRODUCT_LIBRARY_ROW_HEIGHT = PRODUCT_LIBRARY_CARD_HEIGHT + PRODUCT_LIBRARY_GRID_GAP
