package com.colonel.saas.domain.product.application.dto;

/**
 * Query object for the legacy product library page endpoint.
 */
public record ProductLibraryPageQuery(
        String keyword,
        Integer status,
        String shopKeyword,
        String categoryName,
        String categories,
        String activityId,
        String assigneeId,
        String serviceFee,
        String supportsAds,
        String salesRange,
        String promotionLink,
        String allianceStatus,
        String commission,
        String hasSample,
        String assignee,
        String systemTag,
        String decision,
        String partnerId,
        String partnerType,
        String sortBy,
        String goodsTags,
        String productTags,
        String colonelName,
        String published,
        String cooperationType,
        String livePriceMin,
        String livePriceMax,
        String commissionMin,
        String commissionMax,
        String sampleSalesMin,
        String sampleSalesMax,
        String materialDownload,
        String exclusivePrice,
        String productChain,
        String handCard,
        String doubleCommission,
        String notInLibrary,
        String dedup,
        String recruitActivityId,
        String recruitActivityName,
        String listed,
        String freeSample,
        String productId) {
}
