-- Stable controller permission catalog and compatibility grants for built-in roles.
INSERT INTO sys_permission (permission_code, domain_code, resource_code, action_code, data_scope_required, status, deleted, remark)
VALUES
    ('admin-colonel-partner:sync', 'system', 'admin-colonel-partner', 'sync', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('admin-colonel-partner:update-contact', 'system', 'admin-colonel-partner', 'update-contact', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('admin-douyin-quick-sample:access', 'system', 'admin-douyin-quick-sample', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('admin-logistics-gateway:access', 'system', 'admin-logistics-gateway', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('admin-product-display:audit-logs', 'system', 'admin-product-display', 'audit-logs', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('admin-product-display:cancel-force', 'system', 'admin-product-display', 'cancel-force', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('admin-product-display:force-switch', 'system', 'admin-product-display', 'force-switch', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('admin-sample-logistics:access', 'system', 'admin-sample-logistics', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity:access', 'system', 'colonel-activity', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity:assign-activity', 'system', 'colonel-activity', 'assign-activity', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity:trigger-activity-list-sync', 'system', 'colonel-activity', 'trigger-activity-list-sync', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity-product:access', 'system', 'colonel-activity-product', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity-product:assign', 'system', 'colonel-activity-product', 'assign', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity-product:assign-audit-owner', 'system', 'colonel-activity-product', 'assign-audit-owner', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity-product:audit', 'system', 'colonel-activity-product', 'audit', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity-product:batch-assign', 'system', 'colonel-activity-product', 'batch-assign', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity-product:batch-pin', 'system', 'colonel-activity-product', 'batch-pin', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity-product:bind-activity', 'system', 'colonel-activity-product', 'bind-activity', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity-product:decision', 'system', 'colonel-activity-product', 'decision', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity-product:follow', 'system', 'colonel-activity-product', 'follow', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity-product:generate-promotion-link', 'system', 'colonel-activity-product', 'generate-promotion-link', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity-product-library:access', 'system', 'colonel-activity-product-library', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity-product-library:batch-put-into-library', 'system', 'colonel-activity-product-library', 'batch-put-into-library', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity-product-library:put-into-library', 'system', 'colonel-activity-product-library', 'put-into-library', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity-product-pin:access', 'system', 'colonel-activity-product-pin', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity-product-pin:pin-product', 'system', 'colonel-activity-product-pin', 'pin-product', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity-product-pin:unpin-product', 'system', 'colonel-activity-product-pin', 'unpin-product', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-activity-product-query:access', 'system', 'colonel-activity-product-query', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-partner:access', 'system', 'colonel-partner', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-partner-master-data:detail', 'system', 'colonel-partner-master-data', 'detail', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-partner-master-data:list', 'system', 'colonel-partner-master-data', 'list', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-partner-master-data:sources', 'system', 'colonel-partner-master-data', 'sources', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonel-pinned-product:access', 'system', 'colonel-pinned-product', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('colonelsettlement-activity:access', 'system', 'colonelsettlement-activity', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('commission-rule:access', 'system', 'commission-rule', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('dashboard:access', 'system', 'dashboard', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('data:access', 'system', 'data', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('data:export-activities', 'system', 'data', 'export-activities', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('data:export-order-detail', 'system', 'data', 'export-order-detail', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('data:export-orders', 'system', 'data', 'export-orders', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('data:get-exclusive-merchant-status', 'system', 'data', 'get-exclusive-merchant-status', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('data:get-exclusive-talent-status', 'system', 'data', 'get-exclusive-talent-status', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('douyin:access', 'system', 'douyin', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('douyin:chuangjian-huodong', 'system', 'douyin', 'chuangjian-huodong', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('douyin:dingdan-tongbu-yuanshi', 'system', 'douyin', 'dingdan-tongbu-yuanshi', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('douyin:gengxin-huodong', 'system', 'douyin', 'gengxin-huodong', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('douyin:jigou-shenfen', 'system', 'douyin', 'jigou-shenfen', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('douyin:token-create-probe', 'system', 'douyin', 'token-create-probe', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('douyin:token-shuaxin', 'system', 'douyin', 'token-shuaxin', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('douyin:token-zhuangtai', 'system', 'douyin', 'token-zhuangtai', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('douyin:tuiguang-lianjie-yuanshi', 'system', 'douyin', 'tuiguang-lianjie-yuanshi', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('douyin-o-auth:authorize-url', 'system', 'douyin-o-auth', 'authorize-url', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('exclusive-merchant:access', 'system', 'exclusive-merchant', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('merchant:access', 'system', 'merchant', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('merchant:get-partner-detail', 'system', 'merchant', 'get-partner-detail', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('merchant:list-partner-products', 'system', 'merchant', 'list-partner-products', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('merchant:list-partners', 'system', 'merchant', 'list-partners', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('operation-log:access', 'system', 'operation-log', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('order:access', 'system', 'order', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('order:dry-run1603-settlement', 'system', 'order', 'dry-run1603-settlement', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('order:dry-run2704-settlement', 'system', 'order', 'dry-run2704-settlement', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('order:dry-run6468-pagination', 'system', 'order', 'dry-run6468-pagination', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('order:replay-attribution', 'system', 'order', 'replay-attribution', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('order:sync-orders', 'system', 'order', 'sync-orders', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('order:sync-orders-by-range', 'system', 'order', 'sync-orders-by-range', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('order-attribution:access', 'system', 'order-attribution', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('outbox-admin:list', 'system', 'outbox-admin', 'list', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('outbox-admin:retry', 'system', 'outbox-admin', 'retry', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('performance:access', 'system', 'performance', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('performance:export', 'system', 'performance', 'export', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('performance:recalculate-month', 'system', 'performance', 'recalculate-month', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('performance-order-admin:access', 'system', 'performance-order-admin', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('performance-order-admin:performance-backfill', 'system', 'performance-order-admin', 'performance-backfill', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('performance-order-admin:recalculate-single', 'system', 'performance-order-admin', 'recalculate-single', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('performance-order-admin:reconcile-invalidated-performance', 'system', 'performance-order-admin', 'reconcile-invalidated-performance', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product:access', 'system', 'product', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product:admin-counts', 'system', 'product', 'admin-counts', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product:approve-managed-product', 'system', 'product', 'approve-managed-product', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product:assign', 'system', 'product', 'assign', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product:audit', 'system', 'product', 'audit', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product:bind-activity', 'system', 'product', 'bind-activity', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product:detail', 'system', 'product', 'detail', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product:follow', 'system', 'product', 'follow', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product:generate-promotion-link', 'system', 'product', 'generate-promotion-link', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product:page', 'system', 'product', 'page', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product:pause-publish', 'system', 'product', 'pause-publish', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product:promotion-link-history', 'system', 'product', 'promotion-link-history', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product:quick-sample', 'system', 'product', 'quick-sample', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product:reject-managed-product', 'system', 'product', 'reject-managed-product', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product:resume-publish', 'system', 'product', 'resume-publish', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product:update-product-supplement', 'system', 'product', 'update-product-supplement', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product-library-repair:access', 'system', 'product-library-repair', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product-sync-admin:backfill-activity-products', 'system', 'product-sync-admin', 'backfill-activity-products', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product-sync-admin:backfill-activity-products-async', 'system', 'product-sync-admin', 'backfill-activity-products-async', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product-sync-admin:get-backfill-job-status', 'system', 'product-sync-admin', 'get-backfill-job-status', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('product-sync-probe:access', 'system', 'product-sync-probe', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('redis-probe:access', 'system', 'redis-probe', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('rule-center:access', 'system', 'rule-center', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sample:access', 'system', 'sample', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sample:batch-approve', 'system', 'sample', 'batch-approve', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sample:batch-reject', 'system', 'sample', 'batch-reject', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sample:batch-ship', 'system', 'sample', 'batch-ship', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sample:download-logistics-import-template', 'system', 'sample', 'download-logistics-import-template', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sample:export-samples', 'system', 'sample', 'export-samples', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sample:import-logistics-tracking', 'system', 'sample', 'import-logistics-tracking', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sample:refresh-logistics', 'system', 'sample', 'refresh-logistics', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sample:repair-logistics', 'system', 'sample', 'repair-logistics', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sample:sync-all-logistics', 'system', 'sample', 'sync-all-logistics', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sample:sync-logistics', 'system', 'sample', 'sync-logistics', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sys-config:access', 'system', 'sys-config', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sys-config:grouped', 'system', 'sys-config', 'grouped', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sys-dept:access', 'system', 'sys-dept', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sys-menu:all-tree', 'system', 'sys-menu', 'all-tree', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sys-menu:create', 'system', 'sys-menu', 'create', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sys-menu:delete', 'system', 'sys-menu', 'delete', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sys-menu:update', 'system', 'sys-menu', 'update', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sys-role:access', 'system', 'sys-role', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sys-user:access', 'system', 'sys-user', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('sys-user:assignable', 'system', 'sys-user', 'assignable', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('talent:access', 'system', 'talent', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('talent:batch-import', 'system', 'talent', 'batch-import', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('talent:blacklist', 'system', 'talent', 'blacklist', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('talent:override-assignee', 'system', 'talent', 'override-assignee', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('talent:refresh-weekly', 'system', 'talent', 'refresh-weekly', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('talent:talents-by-channel', 'system', 'talent', 'talents-by-channel', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('talent:unblacklist', 'system', 'talent', 'unblacklist', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('talent-profile:access', 'system', 'talent-profile', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('test:access', 'system', 'test', 'access', FALSE, 1, 0, 'Migrated from legacy role guard'),
    ('user-master-data:group-members', 'system', 'user-master-data', 'group-members', FALSE, 1, 0, 'Migrated from legacy role guard')
ON CONFLICT (permission_code) DO UPDATE SET
    domain_code = EXCLUDED.domain_code,
    resource_code = EXCLUDED.resource_code,
    action_code = EXCLUDED.action_code,
    data_scope_required = EXCLUDED.data_scope_required,
    status = EXCLUDED.status,
    deleted = EXCLUDED.deleted,
    update_time = CURRENT_TIMESTAMP;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM (VALUES
    ('admin', 'admin-colonel-partner:sync'),
    ('admin', 'admin-colonel-partner:update-contact'),
    ('admin', 'admin-douyin-quick-sample:access'),
    ('admin', 'admin-logistics-gateway:access'),
    ('admin', 'admin-product-display:audit-logs'),
    ('admin', 'admin-product-display:cancel-force'),
    ('admin', 'admin-product-display:force-switch'),
    ('admin', 'admin-sample-logistics:access'),
    ('admin', 'colonel-activity:access'),
    ('admin', 'colonel-activity:assign-activity'),
    ('admin', 'colonel-activity:trigger-activity-list-sync'),
    ('admin', 'colonel-activity-product:access'),
    ('admin', 'colonel-activity-product:assign'),
    ('admin', 'colonel-activity-product:assign-audit-owner'),
    ('admin', 'colonel-activity-product:audit'),
    ('admin', 'colonel-activity-product:batch-assign'),
    ('admin', 'colonel-activity-product:batch-pin'),
    ('admin', 'colonel-activity-product:bind-activity'),
    ('admin', 'colonel-activity-product:decision'),
    ('admin', 'colonel-activity-product:follow'),
    ('admin', 'colonel-activity-product:generate-promotion-link'),
    ('admin', 'colonel-activity-product-library:access'),
    ('admin', 'colonel-activity-product-library:batch-put-into-library'),
    ('admin', 'colonel-activity-product-library:put-into-library'),
    ('admin', 'colonel-activity-product-pin:access'),
    ('admin', 'colonel-activity-product-pin:pin-product'),
    ('admin', 'colonel-activity-product-pin:unpin-product'),
    ('admin', 'colonel-activity-product-query:access'),
    ('admin', 'colonel-partner:access'),
    ('admin', 'colonel-partner-master-data:detail'),
    ('admin', 'colonel-partner-master-data:list'),
    ('admin', 'colonel-partner-master-data:sources'),
    ('admin', 'colonel-pinned-product:access'),
    ('admin', 'colonelsettlement-activity:access'),
    ('admin', 'commission-rule:access'),
    ('admin', 'dashboard:access'),
    ('admin', 'data:access'),
    ('admin', 'data:export-activities'),
    ('admin', 'data:export-order-detail'),
    ('admin', 'data:export-orders'),
    ('admin', 'data:get-exclusive-merchant-status'),
    ('admin', 'data:get-exclusive-talent-status'),
    ('admin', 'douyin:access'),
    ('admin', 'douyin:chuangjian-huodong'),
    ('admin', 'douyin:dingdan-tongbu-yuanshi'),
    ('admin', 'douyin:gengxin-huodong'),
    ('admin', 'douyin:jigou-shenfen'),
    ('admin', 'douyin:token-create-probe'),
    ('admin', 'douyin:token-shuaxin'),
    ('admin', 'douyin:token-zhuangtai'),
    ('admin', 'douyin:tuiguang-lianjie-yuanshi'),
    ('admin', 'douyin-o-auth:authorize-url'),
    ('admin', 'exclusive-merchant:access'),
    ('admin', 'merchant:access'),
    ('admin', 'merchant:get-partner-detail'),
    ('admin', 'merchant:list-partner-products'),
    ('admin', 'merchant:list-partners'),
    ('admin', 'operation-log:access'),
    ('admin', 'order:access'),
    ('admin', 'order:dry-run1603-settlement'),
    ('admin', 'order:dry-run2704-settlement'),
    ('admin', 'order:dry-run6468-pagination'),
    ('admin', 'order:replay-attribution'),
    ('admin', 'order:sync-orders'),
    ('admin', 'order:sync-orders-by-range'),
    ('admin', 'order-attribution:access'),
    ('admin', 'outbox-admin:list'),
    ('admin', 'outbox-admin:retry'),
    ('admin', 'performance:access'),
    ('admin', 'performance:export'),
    ('admin', 'performance:recalculate-month'),
    ('admin', 'performance-order-admin:access'),
    ('admin', 'performance-order-admin:performance-backfill'),
    ('admin', 'performance-order-admin:recalculate-single'),
    ('admin', 'performance-order-admin:reconcile-invalidated-performance'),
    ('admin', 'product:access'),
    ('admin', 'product:admin-counts'),
    ('admin', 'product:approve-managed-product'),
    ('admin', 'product:assign'),
    ('admin', 'product:audit'),
    ('admin', 'product:bind-activity'),
    ('admin', 'product:detail'),
    ('admin', 'product:follow'),
    ('admin', 'product:generate-promotion-link'),
    ('admin', 'product:page'),
    ('admin', 'product:pause-publish'),
    ('admin', 'product:promotion-link-history'),
    ('admin', 'product:quick-sample'),
    ('admin', 'product:reject-managed-product'),
    ('admin', 'product:resume-publish'),
    ('admin', 'product:update-product-supplement'),
    ('admin', 'product-library-repair:access'),
    ('admin', 'product-sync-admin:backfill-activity-products'),
    ('admin', 'product-sync-admin:backfill-activity-products-async'),
    ('admin', 'product-sync-admin:get-backfill-job-status'),
    ('admin', 'product-sync-probe:access'),
    ('admin', 'redis-probe:access'),
    ('admin', 'rule-center:access'),
    ('admin', 'sample:access'),
    ('admin', 'sample:batch-approve'),
    ('admin', 'sample:batch-reject'),
    ('admin', 'sample:batch-ship'),
    ('admin', 'sample:download-logistics-import-template'),
    ('admin', 'sample:export-samples'),
    ('admin', 'sample:import-logistics-tracking'),
    ('admin', 'sample:refresh-logistics'),
    ('admin', 'sample:repair-logistics'),
    ('admin', 'sample:sync-all-logistics'),
    ('admin', 'sample:sync-logistics'),
    ('admin', 'sys-config:access'),
    ('admin', 'sys-config:grouped'),
    ('admin', 'sys-dept:access'),
    ('admin', 'sys-menu:all-tree'),
    ('admin', 'sys-menu:create'),
    ('admin', 'sys-menu:delete'),
    ('admin', 'sys-menu:update'),
    ('admin', 'sys-role:access'),
    ('admin', 'sys-user:access'),
    ('admin', 'sys-user:assignable'),
    ('admin', 'talent:access'),
    ('admin', 'talent:batch-import'),
    ('admin', 'talent:blacklist'),
    ('admin', 'talent:override-assignee'),
    ('admin', 'talent:refresh-weekly'),
    ('admin', 'talent:talents-by-channel'),
    ('admin', 'talent:unblacklist'),
    ('admin', 'talent-profile:access'),
    ('admin', 'test:access'),
    ('admin', 'user-master-data:group-members'),
    ('biz_leader', 'admin-colonel-partner:sync'),
    ('biz_leader', 'admin-colonel-partner:update-contact'),
    ('biz_leader', 'admin-product-display:audit-logs'),
    ('biz_leader', 'admin-product-display:cancel-force'),
    ('biz_leader', 'admin-product-display:force-switch'),
    ('biz_leader', 'colonel-activity:access'),
    ('biz_leader', 'colonel-activity:trigger-activity-list-sync'),
    ('biz_leader', 'colonel-activity-product:access'),
    ('biz_leader', 'colonel-activity-product:assign'),
    ('biz_leader', 'colonel-activity-product:assign-audit-owner'),
    ('biz_leader', 'colonel-activity-product:batch-assign'),
    ('biz_leader', 'colonel-activity-product:batch-pin'),
    ('biz_leader', 'colonel-activity-product:bind-activity'),
    ('biz_leader', 'colonel-activity-product-library:access'),
    ('biz_leader', 'colonel-activity-product-pin:access'),
    ('biz_leader', 'colonel-activity-product-pin:pin-product'),
    ('biz_leader', 'colonel-activity-product-pin:unpin-product'),
    ('biz_leader', 'colonel-activity-product-query:access'),
    ('biz_leader', 'colonel-partner:access'),
    ('biz_leader', 'colonel-partner-master-data:detail'),
    ('biz_leader', 'colonel-partner-master-data:list'),
    ('biz_leader', 'colonel-partner-master-data:sources'),
    ('biz_leader', 'colonel-pinned-product:access'),
    ('biz_leader', 'colonelsettlement-activity:access'),
    ('biz_leader', 'dashboard:access'),
    ('biz_leader', 'data:access'),
    ('biz_leader', 'data:export-activities'),
    ('biz_leader', 'data:export-order-detail'),
    ('biz_leader', 'data:export-orders'),
    ('biz_leader', 'data:get-exclusive-merchant-status'),
    ('biz_leader', 'data:get-exclusive-talent-status'),
    ('biz_leader', 'exclusive-merchant:access'),
    ('biz_leader', 'merchant:get-partner-detail'),
    ('biz_leader', 'merchant:list-partner-products'),
    ('biz_leader', 'merchant:list-partners'),
    ('biz_leader', 'order:access'),
    ('biz_leader', 'order-attribution:access'),
    ('biz_leader', 'performance:access'),
    ('biz_leader', 'performance:export'),
    ('biz_leader', 'performance-order-admin:access'),
    ('biz_leader', 'product:access'),
    ('biz_leader', 'product:assign'),
    ('biz_leader', 'product:bind-activity'),
    ('biz_leader', 'product:detail'),
    ('biz_leader', 'product:page'),
    ('biz_leader', 'product:pause-publish'),
    ('biz_leader', 'product:promotion-link-history'),
    ('biz_leader', 'product:quick-sample'),
    ('biz_leader', 'product:resume-publish'),
    ('biz_leader', 'product:update-product-supplement'),
    ('biz_leader', 'sample:access'),
    ('biz_leader', 'sample:batch-approve'),
    ('biz_leader', 'sample:batch-reject'),
    ('biz_leader', 'sample:export-samples'),
    ('biz_leader', 'sys-config:grouped'),
    ('biz_leader', 'sys-user:assignable'),
    ('biz_leader', 'user-master-data:group-members'),
    ('biz_staff', 'admin-product-display:audit-logs'),
    ('biz_staff', 'colonel-activity:access'),
    ('biz_staff', 'colonel-activity-product:access'),
    ('biz_staff', 'colonel-activity-product:audit'),
    ('biz_staff', 'colonel-activity-product:batch-pin'),
    ('biz_staff', 'colonel-activity-product:decision'),
    ('biz_staff', 'colonel-activity-product-library:access'),
    ('biz_staff', 'colonel-activity-product-library:batch-put-into-library'),
    ('biz_staff', 'colonel-activity-product-library:put-into-library'),
    ('biz_staff', 'colonel-activity-product-pin:access'),
    ('biz_staff', 'colonel-activity-product-pin:pin-product'),
    ('biz_staff', 'colonel-activity-product-pin:unpin-product'),
    ('biz_staff', 'colonel-activity-product-query:access'),
    ('biz_staff', 'colonel-partner:access'),
    ('biz_staff', 'colonel-partner-master-data:detail'),
    ('biz_staff', 'colonel-partner-master-data:list'),
    ('biz_staff', 'colonel-partner-master-data:sources'),
    ('biz_staff', 'colonel-pinned-product:access'),
    ('biz_staff', 'dashboard:access'),
    ('biz_staff', 'data:access'),
    ('biz_staff', 'exclusive-merchant:access'),
    ('biz_staff', 'merchant:get-partner-detail'),
    ('biz_staff', 'merchant:list-partner-products'),
    ('biz_staff', 'merchant:list-partners'),
    ('biz_staff', 'order:access'),
    ('biz_staff', 'order-attribution:access'),
    ('biz_staff', 'performance:access'),
    ('biz_staff', 'performance-order-admin:access'),
    ('biz_staff', 'product:access'),
    ('biz_staff', 'product:approve-managed-product'),
    ('biz_staff', 'product:audit'),
    ('biz_staff', 'product:detail'),
    ('biz_staff', 'product:page'),
    ('biz_staff', 'product:pause-publish'),
    ('biz_staff', 'product:promotion-link-history'),
    ('biz_staff', 'product:quick-sample'),
    ('biz_staff', 'product:reject-managed-product'),
    ('biz_staff', 'product:resume-publish'),
    ('biz_staff', 'product:update-product-supplement'),
    ('biz_staff', 'sample:access'),
    ('biz_staff', 'sample:batch-approve'),
    ('biz_staff', 'sample:batch-reject'),
    ('biz_staff', 'sample:export-samples'),
    ('biz_staff', 'sys-config:grouped'),
    ('biz_staff', 'talent:access'),
    ('biz_staff', 'talent:batch-import'),
    ('biz_staff', 'talent:blacklist'),
    ('biz_staff', 'talent:refresh-weekly'),
    ('biz_staff', 'talent:unblacklist'),
    ('channel_leader', 'colonel-activity-product:access'),
    ('channel_leader', 'colonel-activity-product:follow'),
    ('channel_leader', 'colonel-activity-product:generate-promotion-link'),
    ('channel_leader', 'colonel-activity-product-library:access'),
    ('channel_leader', 'colonel-activity-product-pin:access'),
    ('channel_leader', 'colonel-activity-product-query:access'),
    ('channel_leader', 'colonel-pinned-product:access'),
    ('channel_leader', 'colonelsettlement-activity:access'),
    ('channel_leader', 'dashboard:access'),
    ('channel_leader', 'data:access'),
    ('channel_leader', 'data:export-activities'),
    ('channel_leader', 'data:export-order-detail'),
    ('channel_leader', 'data:export-orders'),
    ('channel_leader', 'data:get-exclusive-merchant-status'),
    ('channel_leader', 'data:get-exclusive-talent-status'),
    ('channel_leader', 'order:access'),
    ('channel_leader', 'order-attribution:access'),
    ('channel_leader', 'performance:access'),
    ('channel_leader', 'performance:export'),
    ('channel_leader', 'performance-order-admin:access'),
    ('channel_leader', 'product:access'),
    ('channel_leader', 'product:detail'),
    ('channel_leader', 'product:follow'),
    ('channel_leader', 'product:generate-promotion-link'),
    ('channel_leader', 'product:page'),
    ('channel_leader', 'product:promotion-link-history'),
    ('channel_leader', 'product:quick-sample'),
    ('channel_leader', 'sample:access'),
    ('channel_leader', 'sample:batch-approve'),
    ('channel_leader', 'sample:batch-reject'),
    ('channel_leader', 'sys-config:grouped'),
    ('channel_leader', 'sys-dept:access'),
    ('channel_leader', 'sys-user:assignable'),
    ('channel_leader', 'talent:access'),
    ('channel_leader', 'talent:batch-import'),
    ('channel_leader', 'talent:blacklist'),
    ('channel_leader', 'talent:refresh-weekly'),
    ('channel_leader', 'talent:unblacklist'),
    ('channel_leader', 'talent-profile:access'),
    ('channel_leader', 'user-master-data:group-members'),
    ('channel_staff', 'colonel-activity-product:access'),
    ('channel_staff', 'colonel-activity-product:follow'),
    ('channel_staff', 'colonel-activity-product:generate-promotion-link'),
    ('channel_staff', 'colonel-activity-product-library:access'),
    ('channel_staff', 'colonel-activity-product-pin:access'),
    ('channel_staff', 'colonel-activity-product-query:access'),
    ('channel_staff', 'colonel-pinned-product:access'),
    ('channel_staff', 'colonelsettlement-activity:access'),
    ('channel_staff', 'dashboard:access'),
    ('channel_staff', 'data:access'),
    ('channel_staff', 'order:access'),
    ('channel_staff', 'order-attribution:access'),
    ('channel_staff', 'performance:access'),
    ('channel_staff', 'performance-order-admin:access'),
    ('channel_staff', 'product:access'),
    ('channel_staff', 'product:detail'),
    ('channel_staff', 'product:follow'),
    ('channel_staff', 'product:generate-promotion-link'),
    ('channel_staff', 'product:page'),
    ('channel_staff', 'product:promotion-link-history'),
    ('channel_staff', 'product:quick-sample'),
    ('channel_staff', 'sample:access'),
    ('channel_staff', 'sample:batch-approve'),
    ('channel_staff', 'sample:batch-reject'),
    ('channel_staff', 'sys-config:grouped'),
    ('channel_staff', 'talent:access'),
    ('channel_staff', 'talent-profile:access'),
    ('ops_staff', 'admin-douyin-quick-sample:access'),
    ('ops_staff', 'admin-logistics-gateway:access'),
    ('ops_staff', 'admin-sample-logistics:access'),
    ('ops_staff', 'performance:access'),
    ('ops_staff', 'sample:access'),
    ('ops_staff', 'sample:batch-approve'),
    ('ops_staff', 'sample:batch-reject'),
    ('ops_staff', 'sample:batch-ship'),
    ('ops_staff', 'sample:download-logistics-import-template'),
    ('ops_staff', 'sample:export-samples'),
    ('ops_staff', 'sample:import-logistics-tracking'),
    ('ops_staff', 'sample:refresh-logistics'),
    ('ops_staff', 'sample:repair-logistics'),
    ('ops_staff', 'sample:sync-all-logistics'),
    ('ops_staff', 'sample:sync-logistics'),
    ('ops_staff', 'sys-config:grouped')
) AS seed(role_code, permission_code)
JOIN sys_role r ON r.role_code = seed.role_code AND r.deleted = 0
JOIN sys_permission p ON p.permission_code = seed.permission_code
-- Built-in grants are bootstrap defaults only. Once a role has any configured
-- grant, later deployments must preserve the administrator's complete set.
WHERE NOT EXISTS (
    SELECT 1
    FROM sys_role_permission configured
    WHERE configured.role_id = r.id
)
ON CONFLICT (role_id, permission_id) DO NOTHING;
